# Generated by Django 5.1.4 on 2024-12-25 18:07

import frs_attendance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frs_attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='year',
        ),
        migrations.RemoveField(
            model_name='student',
            name='year',
        ),
        migrations.AddField(
            model_name='branch',
            name='batch_start_year',
            field=models.PositiveIntegerField(default=frs_attendance.models.get_current_year),
        ),
    ]
