# Generated by Django 5.1.4 on 2024-12-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frs_attendance', '0002_remove_branch_year_remove_student_year_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name', 'batch_start_year')},
        ),
    ]
