# Generated by Django 5.1.4 on 2025-01-24 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frs_attendance', '0007_remove_student_face_data_student_face_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='face_date',
            new_name='face_data',
        ),
    ]
