# Generated by Django 5.1.4 on 2025-01-24 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frs_attendance', '0008_rename_face_date_student_face_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='face_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
