# Generated by Django 5.0.6 on 2024-06-30 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeshare', '0002_recipeshareuser_following_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
