# Generated by Django 5.0.6 on 2024-07-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeshare', '0009_alter_post_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='favorite',
        ),
        migrations.AddField(
            model_name='recipeshareuser',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorites', to='recipeshare.post'),
        ),
    ]
