# Generated by Django 5.0.6 on 2024-07-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipeshare', '0010_remove_post_favorite_recipeshareuser_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
    ]
