# Generated by Django 5.1.2 on 2024-11-03 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vnapp', '0002_alter_userdata_applydate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='applydate',
            field=models.DateField(),
        ),
    ]
